# Generated by Django 3.2.8 on 2021-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('members', models.ManyToManyField(to='multimodel.Person')),
            ],
        ),
    ]
